import { Retailer, Branch, Product, Special, PriceHistoryPoint, LeaderboardUser } from '../src/types/index.js';

export const RETAILERS: Retailer[] = [
  {
    id: 'picknpay',
    name: 'Pick n Pay',
    logo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#00539B',
    accentColor: '#E31B23',
    verified: true,
    loyaltyProgram: 'Smart Shopper',
  },
  {
    id: 'checkers',
    name: 'Checkers',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#00833E',
    accentColor: '#F58220',
    verified: true,
    loyaltyProgram: 'Xtra Savings',
  },
  {
    id: 'shoprite',
    name: 'Shoprite',
    logo: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#ED1C24',
    accentColor: '#FFCC00',
    verified: true,
    loyaltyProgram: 'Xtra Savings',
  },
  {
    id: 'woolworths',
    name: 'Woolworths Food',
    logo: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#111827',
    accentColor: '#10B981',
    verified: true,
    loyaltyProgram: 'WRewards',
  },
  {
    id: 'spar',
    name: 'SPAR',
    logo: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#007A3D',
    accentColor: '#E30613',
    verified: true,
    loyaltyProgram: 'SPAR Rewards',
  },
  {
    id: 'boxer',
    name: 'Boxer Superstores',
    logo: 'https://images.unsplash.com/photo-1506617564039-2f3b650b7010?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#E30613',
    accentColor: '#FFFFFF',
    verified: true,
    loyaltyProgram: 'Boxer Club',
  },
  {
    id: 'makro',
    name: 'Makro',
    logo: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#003399',
    accentColor: '#FFDF00',
    verified: true,
    loyaltyProgram: 'mCard',
  },
  {
    id: 'game',
    name: 'Game Stores',
    logo: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#EC008C',
    accentColor: '#FFFFFF',
    verified: true,
    loyaltyProgram: 'Game Rewards',
  },
  {
    id: 'dischem',
    name: 'Dis-Chem Pharmacies',
    logo: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#008542',
    accentColor: '#10B981',
    verified: true,
    loyaltyProgram: 'Benefit Programme',
  },
  {
    id: 'clicks',
    name: 'Clicks',
    logo: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=120&q=80',
    primaryColor: '#004B87',
    accentColor: '#00A4E4',
    verified: true,
    loyaltyProgram: 'ClubCard',
  },
];

export const BRANCHES: Branch[] = [
  {
    id: 'b-pnp-seapoint',
    retailer_id: 'picknpay',
    name: 'Pick n Pay Sea Point',
    latitude: -33.918,
    longitude: 18.392,
    address: 'Main Road, Sea Point',
    city: 'Cape Town',
    province: 'Western Cape',
    phone: '021 434 8920',
    opening_hours: 'Open until 18:00',
    verified: true,
  },
  {
    id: 'b-checkers-seapoint',
    retailer_id: 'checkers',
    name: 'Checkers Sea Point',
    latitude: -33.916,
    longitude: 18.389,
    address: 'Regent Road, Sea Point',
    city: 'Cape Town',
    province: 'Western Cape',
    phone: '021 430 4000',
    opening_hours: 'Open until 20:00',
    verified: true,
  },
  {
    id: 'b-pnp-vna',
    retailer_id: 'picknpay',
    name: 'Pick n Pay V&A Waterfront',
    latitude: -33.905,
    longitude: 18.421,
    address: 'Breakwater Blvd, Victoria & Alfred Waterfront',
    city: 'Cape Town',
    province: 'Western Cape',
    phone: '021 418 5000',
    opening_hours: 'Open until 21:00',
    verified: true,
  },
  {
    id: 'b-checkers-kloof',
    retailer_id: 'checkers',
    name: 'Checkers Kloof Street',
    latitude: -33.931,
    longitude: 18.411,
    address: 'Kloof St, Gardens',
    city: 'Cape Town',
  },
  {
    id: 'b-woolies-cavendish',
    retailer_id: 'woolworths',
    name: 'Woolworths Food Cavendish Square',
    latitude: -33.981,
    longitude: 18.465,
    address: 'Cavendish Square, Dreyer St, Claremont',
    city: 'Cape Town',
  },
  {
    id: 'b-shoprite-cbd',
    retailer_id: 'shoprite',
    name: 'Shoprite Golden Acre',
    latitude: -33.923,
    longitude: 18.424,
    address: 'Adderley St & Strand St',
    city: 'Cape Town',
  },
  {
    id: 'b-spar-seapoint',
    retailer_id: 'spar',
    name: 'SUPERSPAR Sea Point',
    latitude: -33.916,
    longitude: 18.388,
    address: 'Regent Rd, Sea Point',
    city: 'Cape Town',
  },
  {
    id: 'b-makro-milnerton',
    retailer_id: 'makro',
    name: 'Makro Cape Gate / Milnerton',
    latitude: -33.882,
    longitude: 18.514,
    address: 'Plattekloof Rd, Montague Gardens',
    city: 'Cape Town',
  },
  {
    id: 'b-dischem-canal',
    retailer_id: 'dischem',
    name: 'Dis-Chem Canal Walk',
    latitude: -33.892,
    longitude: 18.512,
    address: 'Century Blvd, Century City',
    city: 'Cape Town',
  },
  {
    id: 'b-clicks-gardens',
    retailer_id: 'clicks',
    name: 'Clicks Gardens Centre',
    latitude: -33.935,
    longitude: 18.415,
    address: 'Mill St, Oranjezicht',
    city: 'Cape Town',
  },
  // Gauteng Branches
  {
    id: 'b-checkers-sandton',
    retailer_id: 'checkers',
    name: 'Checkers Hyper Sandton City',
    latitude: -26.108,
    longitude: 28.053,
    address: 'Rivonia Rd, Sandhurst, Sandton',
    city: 'Johannesburg',
  },
  {
    id: 'b-pnp-rosebank',
    retailer_id: 'picknpay',
    name: 'Pick n Pay Rosebank Mall',
    latitude: -26.146,
    longitude: 28.043,
    address: 'Bath Ave, Rosebank',
    city: 'Johannesburg',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p-coke-2l',
    brand: 'Coca-Cola',
    name: 'Coca-Cola Original Less Sugar 2L',
    barcode: '6001108000018',
    category: 'Groceries',
    unit_size: '2L',
  },
  {
    id: 'p-milk-2l',
    brand: 'Clover',
    name: 'Clover Fresh Full Cream Milk 2L',
    barcode: '6001299013019',
    category: 'Groceries',
    unit_size: '2L',
  },
  {
    id: 'p-bread-700g',
    brand: 'Albany',
    name: 'Albany Superior White Bread 700g',
    barcode: '6001007010408',
    category: 'Groceries',
    unit_size: '700g',
  },
  {
    id: 'p-chicken-1kg',
    brand: "Farmer's Choice",
    name: 'Fresh Mixed Chicken Braai Pack 1kg',
    barcode: '6009802001123',
    category: 'Meat',
    unit_size: '1kg',
  },
  {
    id: 'p-boerewors-1kg',
    brand: 'Grabouw',
    name: 'Traditional Champion Boerewors 1kg',
    barcode: '6009612345678',
    category: 'Meat',
    unit_size: '1kg',
  },
  {
    id: 'p-eggs-18',
    brand: 'Nulaid',
    name: 'Nulaid Extra Large Eggs 18s',
    barcode: '6001008012019',
    category: 'Fresh Produce',
    unit_size: '18 pack',
  },
  {
    id: 'p-pampers-s4',
    brand: 'Pampers',
    name: 'Pampers Premium Care Size 4 Jumbo',
    barcode: '4015400612345',
    category: 'Baby',
    unit_size: '52 pack',
  },
  {
    id: 'p-coffee-200g',
    brand: 'Jacobs',
    name: 'Jacobs Krönung Instant Coffee 200g',
    barcode: '8711000508008',
    category: 'Groceries',
    unit_size: '200g',
  },
  {
    id: 'p-sunlight-750ml',
    brand: 'Sunlight',
    name: 'Sunlight Dishwashing Liquid Lemon 750ml',
    barcode: '6001087352313',
    category: 'Household',
    unit_size: '750ml',
  },
  {
    id: 'p-panado-24',
    brand: 'Panado',
    name: 'Panado Paracetamol Tablets 500mg 24s',
    barcode: '6001306000215',
    category: 'Pharmacy',
    unit_size: '24 tablets',
  },
];

export const INITIAL_SPECIALS: Special[] = [
  {
    id: 's-1',
    product_id: 'p-coke-2l',
    product_name: 'Coca-Cola Original 2L',
    brand: 'Coca-Cola',
    unit_size: '2L',
    category: 'Groceries',
    branch_id: 'b-pnp-seapoint',
    branch_name: 'Pick n Pay Sea Point',
    branch_address: 'Main Road, Sea Point',
    retailer_id: 'picknpay',
    retailer_name: 'Pick n Pay',
    price: 19.99,
    original_price: 29.99,
    savings: 10.0,
    savings_percentage: 34,
    expires_at: '2026-09-18T23:59:59Z',
    confidence_score: 98.4,
    promotion_text: 'Smart Shopper Price • Valid until Sunday',
    image_url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
    user_id: 'u-dealhunter',
    user_name: 'Shaheen E.',
    user_username: '@DealHunter',
    user_reputation_title: 'Trusted Contributor',
    user_reputation: 2840,
    created_at: '12 min ago',
    verified_count: 18,
    distance_km: 1.4,
    drive_time_mins: 8,
    walk_time_mins: 18,
  },
  {
    id: 's-2',
    product_id: 'p-milk-2l',
    product_name: 'Clover Fresh Full Cream Milk 2L',
    brand: 'Clover',
    unit_size: '2L',
    category: 'Groceries',
    branch_id: 'b-checkers-kloof',
    branch_name: 'Checkers Kloof Street',
    retailer_id: 'checkers',
    retailer_name: 'Checkers',
    price: 27.99,
    original_price: 34.99,
    savings: 7.0,
    savings_percentage: 20,
    expires_at: '2026-09-16T23:59:59Z',
    confidence_score: 96.2,
    promotion_text: 'Xtra Savings Deal • Swipe to save',
    image_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    user_id: 'u-thabo',
    user_name: 'Thabo M.',
    user_reputation: 2450,
    created_at: '28 minutes ago',
    verified_count: 22,
    distance_km: 2.1,
  },
  {
    id: 's-3',
    product_id: 'p-boerewors-1kg',
    product_name: 'Traditional Champion Boerewors 1kg',
    brand: 'Grabouw',
    unit_size: '1kg',
    category: 'Meat',
    branch_id: 'b-checkers-kloof',
    branch_name: 'Checkers Kloof Street',
    retailer_id: 'checkers',
    retailer_name: 'Checkers',
    price: 79.99,
    original_price: 99.99,
    savings: 20.0,
    savings_percentage: 20,
    expires_at: '2026-09-20T23:59:59Z',
    confidence_score: 99.1,
    promotion_text: 'Heritage Weekend Braai Special!',
    image_url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80',
    user_id: 'u-sipho',
    user_name: 'Sipho D.',
    user_reputation: 1780,
    created_at: '45 minutes ago',
    verified_count: 31,
    distance_km: 2.1,
  },
  {
    id: 's-4',
    product_id: 'p-eggs-18',
    product_name: 'Nulaid Extra Large Eggs 18s',
    brand: 'Nulaid',
    unit_size: '18 pack',
    category: 'Fresh Produce',
    branch_id: 'b-woolies-cavendish',
    branch_name: 'Woolworths Cavendish',
    retailer_id: 'woolworths',
    retailer_name: 'Woolworths Food',
    price: 49.99,
    original_price: 64.99,
    savings: 15.0,
    savings_percentage: 23,
    expires_at: '2026-09-17T23:59:59Z',
    confidence_score: 97.5,
    promotion_text: 'Buy 1 Get WRewards 20% Off',
    image_url: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=600&q=80',
    user_id: 'u-amy',
    user_name: 'Amy van der Merwe',
    user_reputation: 3100,
    created_at: '1 hour ago',
    verified_count: 18,
    distance_km: 5.6,
  },
  {
    id: 's-5',
    product_id: 'p-coffee-200g',
    product_name: 'Jacobs Krönung Instant Coffee 200g',
    brand: 'Jacobs',
    unit_size: '200g',
    category: 'Groceries',
    branch_id: 'b-shoprite-cbd',
    branch_name: 'Shoprite Golden Acre',
    retailer_id: 'shoprite',
    retailer_name: 'Shoprite',
    price: 89.99,
    original_price: 129.99,
    savings: 40.0,
    savings_percentage: 31,
    expires_at: '2026-09-19T23:59:59Z',
    confidence_score: 95.0,
    promotion_text: 'Lowest Price Guarantee • Max 4 per customer',
    image_url: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=600&q=80',
    user_id: 'u-devin',
    user_name: 'Devin P.',
    user_reputation: 980,
    created_at: '2 hours ago',
    verified_count: 9,
    distance_km: 0.8,
  },
  {
    id: 's-6',
    product_id: 'p-pampers-s4',
    product_name: 'Pampers Premium Care Size 4 Jumbo 52s',
    brand: 'Pampers',
    unit_size: '52 pack',
    category: 'Baby',
    branch_id: 'b-dischem-canal',
    branch_name: 'Dis-Chem Canal Walk',
    retailer_id: 'dischem',
    retailer_name: 'Dis-Chem',
    price: 219.99,
    original_price: 289.99,
    savings: 70.0,
    savings_percentage: 24,
    expires_at: '2026-09-21T23:59:59Z',
    confidence_score: 99.4,
    promotion_text: 'Baby Month Special • Benefit Cardholders Only',
    image_url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=600&q=80',
    user_id: 'u-fatima',
    user_name: 'Fatima B.',
    user_reputation: 4200,
    created_at: '3 hours ago',
    verified_count: 45,
    distance_km: 6.8,
    branch_address: 'Century Blvd, Century City',
    user_username: '@FatimaSaver',
    user_reputation_title: 'iShopp Champion',
    drive_time_mins: 15,
    walk_time_mins: 55,
  },
  {
    id: 's-7',
    product_id: 'p-bread-700g',
    product_name: 'Albany Superior White Bread 700g',
    brand: 'Albany',
    unit_size: '700g',
    category: 'Groceries',
    branch_id: 'b-pnp-seapoint',
    branch_name: 'Pick n Pay Sea Point',
    branch_address: 'Main Road, Sea Point',
    retailer_id: 'picknpay',
    retailer_name: 'Pick n Pay',
    price: 14.99,
    original_price: 19.99,
    savings: 5.0,
    savings_percentage: 25,
    expires_at: '2026-09-19T23:59:59Z',
    confidence_score: 99.0,
    promotion_text: 'Fresh Bakery Daily Special',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    user_id: 'u-dealhunter',
    user_name: 'Shaheen E.',
    user_username: '@DealHunter',
    user_reputation_title: 'Trusted Contributor',
    user_reputation: 2840,
    created_at: '25 min ago',
    verified_count: 12,
    distance_km: 1.4,
    drive_time_mins: 8,
    walk_time_mins: 18,
  },
  {
    id: 's-8',
    product_id: 'p-milk-2l',
    product_name: 'Clover Fresh Full Cream Milk 2L',
    brand: 'Clover',
    unit_size: '2L',
    category: 'Groceries',
    branch_id: 'b-pnp-seapoint',
    branch_name: 'Pick n Pay Sea Point',
    branch_address: 'Main Road, Sea Point',
    retailer_id: 'picknpay',
    retailer_name: 'Pick n Pay',
    price: 24.99,
    original_price: 34.99,
    savings: 10.0,
    savings_percentage: 29,
    expires_at: '2026-09-18T23:59:59Z',
    confidence_score: 98.0,
    promotion_text: 'Smart Shopper Special • 2L Fresh',
    image_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    user_id: 'u-dealhunter',
    user_name: 'Shaheen E.',
    user_username: '@DealHunter',
    user_reputation_title: 'Trusted Contributor',
    user_reputation: 2840,
    created_at: '30 min ago',
    verified_count: 20,
    distance_km: 1.4,
    drive_time_mins: 8,
    walk_time_mins: 18,
  },
  {
    id: 's-9',
    product_id: 'p-coke-2l',
    product_name: 'Coca-Cola Original 2L',
    brand: 'Coca-Cola',
    unit_size: '2L',
    category: 'Groceries',
    branch_id: 'b-checkers-seapoint',
    branch_name: 'Checkers Sea Point',
    branch_address: 'Regent Road, Sea Point',
    retailer_id: 'checkers',
    retailer_name: 'Checkers',
    price: 21.99,
    original_price: 29.99,
    savings: 8.0,
    savings_percentage: 27,
    expires_at: '2026-09-17T23:59:59Z',
    confidence_score: 97.2,
    promotion_text: 'Xtra Savings Deal',
    image_url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
    user_id: 'u-thabo',
    user_name: 'Thabo M.',
    user_username: '@ShopperSA',
    user_reputation_title: 'Level 8 • 94% verified',
    user_reputation: 2450,
    created_at: '40 min ago',
    verified_count: 16,
    distance_km: 1.1,
    drive_time_mins: 6,
    walk_time_mins: 14,
  },
];

// Price Intelligence History (Faithfully representing IMG-20260912-WA0000.jpg)
export const PRICE_HISTORY: Record<string, PriceHistoryPoint[]> = {
  'p-milk-2l': [
    {
      id: 'ph-1',
      product_id: 'p-milk-2l',
      date: '2026-09-07',
      day_label: 'Monday',
      price: 34.0,
      original_price: 34.0,
      retailer_id: 'picknpay',
      retailer_name: 'Pick n Pay',
    },
    {
      id: 'ph-2',
      product_id: 'p-milk-2l',
      date: '2026-09-08',
      day_label: 'Tuesday',
      price: 31.0,
      original_price: 34.0,
      retailer_id: 'checkers',
      retailer_name: 'Checkers',
    },
    {
      id: 'ph-3',
      product_id: 'p-milk-2l',
      date: '2026-09-11',
      day_label: 'Friday',
      price: 27.99,
      original_price: 34.0,
      retailer_id: 'checkers',
      retailer_name: 'Checkers',
    },
  ],
  'p-coke-2l': [
    {
      id: 'ph-4',
      product_id: 'p-coke-2l',
      date: '2026-09-05',
      day_label: 'Saturday',
      price: 28.99,
      retailer_id: 'spar',
      retailer_name: 'SPAR',
    },
    {
      id: 'ph-5',
      product_id: 'p-coke-2l',
      date: '2026-09-08',
      day_label: 'Tuesday',
      price: 24.99,
      retailer_id: 'checkers',
      retailer_name: 'Checkers',
    },
    {
      id: 'ph-6',
      product_id: 'p-coke-2l',
      date: '2026-09-12',
      day_label: 'Today',
      price: 19.99,
      retailer_id: 'picknpay',
      retailer_name: 'Pick n Pay',
    },
  ],
  'p-boerewors-1kg': [
    {
      id: 'ph-7',
      product_id: 'p-boerewors-1kg',
      date: '2026-09-01',
      day_label: 'Last Week',
      price: 109.99,
      retailer_id: 'woolworths',
      retailer_name: 'Woolworths',
    },
    {
      id: 'ph-8',
      product_id: 'p-boerewors-1kg',
      date: '2026-09-09',
      day_label: 'Wednesday',
      price: 94.99,
      retailer_id: 'picknpay',
      retailer_name: 'Pick n Pay',
    },
    {
      id: 'ph-9',
      product_id: 'p-boerewors-1kg',
      date: '2026-09-12',
      day_label: 'Today',
      price: 79.99,
      retailer_id: 'checkers',
      retailer_name: 'Checkers',
    },
  ],
};

export const LEADERBOARD: LeaderboardUser[] = [
  {
    id: 'u-fatima',
    name: 'Fatima B.',
    city: 'Cape Town',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    contribution_score: 4200,
    reputation_score: 99,
    scans_count: 84,
    rank: 1,
    badge: 'Top Contributor',
  },
  {
    id: 'u-amy',
    name: 'Amy van der Merwe',
    city: 'Stellenbosch',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    contribution_score: 3100,
    reputation_score: 96,
    scans_count: 62,
    rank: 2,
    badge: 'Grocery Hero',
  },
  {
    id: 'u-thabo',
    name: 'Thabo M.',
    city: 'Johannesburg',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    contribution_score: 2450,
    reputation_score: 94,
    scans_count: 49,
    rank: 3,
    badge: 'Deal Hunter',
  },
  {
    id: 'u-lerato',
    name: 'Lerato K.',
    city: 'Cape Town',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    contribution_score: 1920,
    reputation_score: 92,
    scans_count: 38,
    rank: 4,
    badge: 'Weekend Warrior',
  },
  {
    id: 'u-sipho',
    name: 'Sipho D.',
    city: 'Durban',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    contribution_score: 1780,
    reputation_score: 89,
    scans_count: 35,
    rank: 5,
    badge: 'Deal Hunter',
  },
];
